# Generated by Django 5.1.4 on 2024-12-10 23:35

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=10)),
                ('base_salary', models.DecimalField(decimal_places=2, default=30000.0, max_digits=10)),
                ('prime_name_1', models.CharField(default='Risque', max_length=50)),
                ('prime_value_1', models.IntegerField(default=0)),
                ('cns_1', models.BooleanField(default=True)),
                ('irg_1', models.BooleanField(default=True)),
                ('prime_name_2', models.CharField(blank=True, default='Rendement_Collectif', max_length=50)),
                ('prime_value_2', models.IntegerField(default=0)),
                ('cns_2', models.BooleanField(default=True)),
                ('irg_2', models.BooleanField(default=True)),
                ('prime_name_3', models.CharField(blank=True, default='Productivity', max_length=50)),
                ('prime_value_3', models.IntegerField(default=0)),
                ('cns_3', models.BooleanField(default=True)),
                ('irg_3', models.BooleanField(default=True)),
                ('prime_name_4', models.CharField(blank=True, default='Assiduite', max_length=50)),
                ('prime_value_4', models.IntegerField(default=0)),
                ('cns_4', models.BooleanField(default=True)),
                ('irg_4', models.BooleanField(default=True)),
                ('prime_name_5', models.CharField(blank=True, default='Mession', max_length=50)),
                ('prime_value_5', models.IntegerField(default=0)),
                ('cns_5', models.BooleanField(default=False)),
                ('irg_5', models.BooleanField(default=False)),
                ('prime_name_6', models.CharField(blank=True, default='Transport', max_length=50)),
                ('prime_value_6', models.IntegerField(default=0)),
                ('cns_6', models.BooleanField(default=False)),
                ('irg_6', models.BooleanField(default=False)),
                ('prime_name_7', models.CharField(blank=True, default='Fin_Annee', max_length=50)),
                ('prime_value_7', models.IntegerField(default=0)),
                ('cns_7', models.BooleanField(default=False)),
                ('irg_7', models.BooleanField(default=False)),
                ('prime_name_8', models.CharField(blank=True, default='Occastionnelle', max_length=50)),
                ('prime_value_8', models.IntegerField(default=0)),
                ('cns_8', models.BooleanField(default=False)),
                ('irg_8', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Annual', 'Annual Leave'), ('Maternity', 'Maternity Leave'), ('Paternity', 'Paternity Leave'), ('Unpaid', 'Unpaid Leave')], default='Sick', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='HR_WebApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
