# Generated by Django 5.1.4 on 2024-12-11 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR_WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('Net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prime_name_1', models.CharField(default='Risque', max_length=50)),
                ('prime_value_1', models.IntegerField(default=0)),
                ('cns_1', models.BooleanField(default=True)),
                ('irg_1', models.BooleanField(default=True)),
                ('prime_name_2', models.CharField(blank=True, default='Rendement_Collectif', max_length=50)),
                ('prime_value_2', models.IntegerField(default=0)),
                ('cns_2', models.BooleanField(default=True)),
                ('irg_2', models.BooleanField(default=True)),
                ('prime_name_3', models.CharField(blank=True, default='Productivity', max_length=50)),
                ('prime_value_3', models.IntegerField(default=0)),
                ('cns_3', models.BooleanField(default=True)),
                ('irg_3', models.BooleanField(default=True)),
                ('prime_name_4', models.CharField(blank=True, default='Assiduite', max_length=50)),
                ('prime_value_4', models.IntegerField(default=0)),
                ('cns_4', models.BooleanField(default=True)),
                ('irg_4', models.BooleanField(default=True)),
                ('prime_name_5', models.CharField(blank=True, default='Mession', max_length=50)),
                ('prime_value_5', models.IntegerField(default=0)),
                ('cns_5', models.BooleanField(default=False)),
                ('irg_5', models.BooleanField(default=False)),
                ('prime_name_6', models.CharField(blank=True, default='Transport', max_length=50)),
                ('prime_value_6', models.IntegerField(default=0)),
                ('cns_6', models.BooleanField(default=False)),
                ('irg_6', models.BooleanField(default=False)),
                ('prime_name_7', models.CharField(blank=True, default='Fin_Annee', max_length=50)),
                ('prime_value_7', models.IntegerField(default=0)),
                ('cns_7', models.BooleanField(default=False)),
                ('irg_7', models.BooleanField(default=False)),
                ('prime_name_8', models.CharField(blank=True, default='Occastionnelle', max_length=50)),
                ('prime_value_8', models.IntegerField(default=0)),
                ('cns_8', models.BooleanField(default=False)),
                ('irg_8', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='HR_WebApp.employee')),
            ],
        ),
    ]
